version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: inventory_db2

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: IMS_backend

    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FRONTEND_URL: ${FRONTEND_URL}

    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: IMS_frontend

    restart: unless-stopped

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: ${VITE_API_URL}

    depends_on:
      - backend


volumes:
  postgres_data: